name: deploy-github-page

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: twtug/lkmpg

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make html
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages
